baseURL = "https://dameuncoctel.netlify.app/"
languageCode = "es"
title = "DAMeuncoctel"
themesDir = "themes"
theme = "hugo-hero-theme"



[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.png"
    desktop_height = "200px"
    desktop_width = "200px"
    alt = "dameuncoctel logo"

  [params.homepage_meta_tags]
    meta_description = "DAMeuncoctel es una aplicacion pensada para disfrutar de los cocteles y esta es la pagina web de presentacion"
    meta_og_title = "DAMeuncoctel webpage"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = ""
    meta_og_description = "DAMeuncoctel es una aplicacion pensada para disfrutar de los cocteles y esta es la pagina web de presentacion."
    meta_twitter_card = "summary"
    meta_twitter_site = "@dameuncoctel"
    meta_twitter_creator = "@dameuncoctel"

[[menu.main]]
	name = "Características"
	url = "/caracteristicas/"
    weight = 1

[[menu.main]]
    name = "Diseño"
    url = "/diseño/"
    weight = 2

[[menu.main]]
    name = "Conocenos"
    url = "/conócenos/"
    weight = 3


[[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
